### ISSUE TITLE
v1.8.4 Condition & Status is Unknown (Also v2/Stargate)

### ISSUE THREAD

**Issue by lightiv** [forbole/bdjuno#294]
## Bug description

This build did not show a "condition" but the "status" did display.  Unfortunately, some validators started appearing on the inactive table.  To resolve this I delete all data from the database and resync'd.  Everything appears fine except this problem.

![image](https://user-images.githubusercontent.com/36428473/146604781-d28163fd-c1c4-4b2a-9cb9-746165d3e027.png)

See: https://gravity-bridge.skynetexplorers.com/

## Steps to reproduce

I built bdjuno using the custom chain instructions.  This worked without error and intially the status was "Status" was known but the "condition" was not.  Nodes begain showing in the "inactive" tab on the validator page.  If you click on any of the validators they will show as "active" with is correct.

I opened an Issue under BD2.0  (https://github.com/forbole/big-dipper-2.0-cosmos/issues/607).  We tested a query that shows the status is not being inserted in to the status table.  See scrip in issue 607.

## Expected behavior

Condition and status will be imported into the database and displyed properly in BD2.0 UI

**Comment by rmontagnin** [comment]
@lightiv Can you please add a Pastebin link with your BDJuno config? Or add the config directly here

**Comment by lightiv** [comment]
```yaml
chain:
    bech32_prefix: gravity
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - pricefeed
        - slashing
        - staking
        - distribution
        - history
        - telemetry
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: http://localhost:9090
            insecure: true
parsing:
    workers: 6
    listen_new_blocks: true
    parse_old_blocks: true
    genesis_file_path: /home/$USER/.gravity/config/genesis.json
    parse_genesis: true
    start_height: 1
database:
    name: juno
    host: localhost
    port: 5432
    user: $USER
    password: <my_password>
    schema: public
    max_open_connections: 5
    max_idle_connections: 5
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed:
    tokens:
        - name: Cosmos Gravity Bridge
          units:
            - denom: ugraviton
              exponent: 0
            - denom: graviton
              exponent: 6
distribution:
    rewards_frequency: 100
```
