### ISSUE TITLE
Unable to parse `genesis.json` file

### ISSUE THREAD

**Issue by arnabghose997** [forbole/bdjuno#316]
I have scaffolded a cosmos chain using `starport` which is named `hid-node`. While going through the docs for setting up bdjuno (https://docs.bigdipper.live/cosmos-based/parser/setup), things were fine until the `bdjuno init` section. But I am now facing an issue while trying to parse the genesis file using the command `bdjuno parse-genesis`

 Following is the error:
```
ERROR: error while getting genesis doc and state: failed to read genesis file: open ~/.hid-node/config/genesis.json: no such file or directory
``` 

I cross checked the genesis path, which was correct.

Following is the bdjuno `config.yaml` I used:

```
chain:
    bech32_prefix: cosmos
    modules: 
        - modules
        - messages
        - auth
node:
    type: remote
    config:
        rpc:
            client_name: hidnode
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: http://localhost:9095
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    genesis_file_path: ~/.hid-node/config/genesis.json
database:
    name: postgres
    host: localhost
    port: 5432
    user: postgres
    password: password
    schema: public
    max_open_connections: 10
    max_idle_connections: 10
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed:
    tokens:
        - name: Atom
          units:
            - denom: uatom
              exponent: 0
            - denom: atom
              exponent: 6
              price_id: cosmos
distribution:
    rewards_frequency: 100
```
