### ISSUE TITLE
Can you please explain why this error is showing up in bdjuno logs?

### ISSUE THREAD

**Issue by lohanspies** [forbole/bdjuno#347]
`getting this error from bdjuno `bdjuno[4820]: 2:19PM ERR error while getting staking pool error="error while getting staking pool: rpc error: code = Unknown desc = panic message redacted to hide potentially sensitive system info: panic" height=2654 module=staking`

**Comment by huichiaotsou** [comment]
Hi @lohanspies thanks for the request. Would you mind sharing more information about which chain, which version of bdjuno, and what is the config file look like etc, so we can investigate? If possible provide me with the rpc/gprc endpoint being used.

**Comment by lohanspies** [comment]
@huichiaotsou it is for the IXO chain. Executing `bdjuno version` doesn't provide any version information. But pulled from the latest main branch.  Please find the bdjuno config below. The RPC and gRPC endpoints are protected by a firewall and not available to the world. If possible we can chat on Discord, Telegram, Slack to discuss further?

```
chain:
    bech32_prefix: ixo
    modules: 
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - pricefeed
        - slashing
        - staking
        - distribution
        - history
node:
    type: remote
    config:
        rpc:
            client_name: ixo
            address: http://{{IP}}:26657
            max_connections: 20
        grpc:
            address: http://{{IP}}:9090
            insecure: true
parsing:
    workers: 5
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    genesis_file_path: ixo_genesis.json
database:
    name: {{DBNAME}}
    host: localhost
    port: 5432
    user: {{USER}}
    password: {{PASSWORD}}
    schema: public
    max_open_connections: 10
    max_idle_connections: 10
logging:
    level: debug
    format: text
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed:
    tokens:
        - name: ixo
          units:
            - denom: uixo
              exponent: 0
            - denom: ixo
              exponent: 6
              price_id: ixo
distribution:
    rewards_frequency: 100
```
