### ISSUE TITLE
cmd hasura-actions uses localhost as connection string ignoring config reference

### ISSUE THREAD

**Issue by justyntemme** [forbole/bdjuno#365]
When running `bdjuno hasura-actions` I am receiving this error. 

```
12:19PM INF Listening to incoming Hasura actions requests.... grpc=[http://127.0.0.1:9090]() rpc=[http://127.0.0.1:26657]() secure=false
ERROR: dial tcp 127.0.0.1:26657: connectex: No connection could be made because the target machine actively refused it.
```
Below is our config.yaml which has the node rpc config already set

```
chain:
    bech32_prefix: cosmos
    modules: []
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://rpc.testnet.pylons.tech:26657
            max_connections: 20
        grpc:
            address: http://grpc.testnet.pylons.tech:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
database:
    name: bdjuno
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
logging:
    level: debug
    format: text
telemetry:
    port: 500
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed: null

```
Is hasura-actions expecting a different config parameter that's missing from the documentation reference?

using v2.0.0
