### ISSUE TITLE
Implement template in hasura actions

### ISSUE THREAD

**Issue by AlexanderNtk** [forbole/bdjuno#373]
## Feature description 
Add `ACTION_BASE_URL` environment variable for hasura container to make it work with BDJuno outside of container.
When you import hasura metadata, actions endpoint is hardcoded `http://localhost:3000/account_balance`, but it brakes
containered hasura deployment.

## Implementation proposal
In `actions.yaml` file handlers localhost should be replaced with name on environment variable.
eg:
### Current value:
```
- name: action_account_balance
  definition:
    kind: synchronous
    handler: http://localhost:3000/account_balance
    output_type: ActionBalance
    arguments:
    - name: address
      type: String!
    - name: height
      type: Int
    type: query
    headers:
    - value: application/json
      name: Content-Type
  permissions:
  - role: anonymous
```
### New value:
```
- name: action_account_balance
  definition:
    kind: synchronous
    handler: http://{{ACTION_BASE_URL}}/account_balance
    output_type: ActionBalance
    arguments:
    - name: address
      type: String!
    - name: height
      type: Int
    type: query
    headers:
    - value: application/json
      name: Content-Type
  permissions:
  - role: anonymous
```
After that anyone can start container with  additional environment variable `-e ACTION_BASE_URL="192.168.1.2:3000"` to use BDJuno outside hasura container.
