### ISSUE TITLE
Error on `bdjuno start`

### ISSUE THREAD

**Issue by jessepinkman9900** [forbole/bdjuno#433]
## Bug description

Upon running `bdjuno start`
Get the following error `ERROR: failed to start client: failed to initialize database: resource temporarily unavailable`

### Other Info
- `systemctl status postgresql@14-main.service` shows `active (running)`
### Config
```yml
# database section of config.yml
database:
    name: <database-name>
    host: localhost
    port: 5432
    user: <user>
    password: <password>
    schema: public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
```

### Question
What does this error mean? 
1. Does it mean that my database config is wrong? OR
2. Does it mean that there is some issue with the database migration done in Postgres? If yes, are there any changes to make in the database scripts for custom chains?

**Comment by huichiaotsou** [comment]
Hi @jessepinkman9900,

your db config looks okay, could you share your complete `config.yaml` file ? What's the node type you've configured? If the type is `local` it means the bdjuno should read from a static node that's not running. If you run `bdjuno of node.type local` on a running node/chain it will create error that means your chain's db is currently being occupied and then it's not allowed to be read by another program. More info about [the node config](https://docs.bigdipper.live/cosmos-based/parser/config/config#node).

**Comment by jessepinkman9900** [comment]
### Config
```yml
chain:
    bech32_prefix: evmos
    modules:
        - actions
node:
    type: local
    config:
        home: /home/ubuntu/.evmosd
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 5s
database:
    name:<database-name>
    host: localhost
    port: 5432
    user: <user>
    password: <password>
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    port: 3000
```

the node was setup as type `local`, will try it as `remote` with `localhost` urls
Suggestion to add this detail about bdjuno not being able to read from chain db on a live chain to docs
