### ISSUE TITLE
Proposals and transactions on chain from before bdjuno started running don't show up

### ISSUE THREAD

**Issue by makew0rld** [forbole/bdjuno#451]
## Bug description

I am running bdjuno on the Theta testnet. Proposals made after genesis but before bdjuno started, don't show up. No transactions show up at all except those that happened after bdjuno was running.

Here is the parsing section of my config:

```yaml
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    genesis_file_path: {{bdjuno_home}}/genesis.json
    average_block_time: 3s
```

I have been running bdjuno for ~43 hours. Is it just that it needs more time to go through the blockchain? I would have expected some old transactions to show up by now though.

When I switched to `workers: 10` CPU spiked for a bit after restarting bdjuno, but then fell back down. No DB change was observed, no old stuff appeared.

## Steps to reproduce

Install and run bdjuno on the Theta testnet. I have an ansible role in [this PR](https://github.com/hyphacoop/cosmos-ansible/pull/6).

## Expected behavior

Old proposals and transactions would appear.
