### ISSUE TITLE
Issue running bdjuno locally 

### ISSUE THREAD

**Issue by devashar13** [forbole/bdjuno#468]
I have configured my config.json
```
chain:
    bech32_prefix: cosmos
    modules:
      - modules
      - messages
      - auth

node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: https://cosmos-mainnet-rpc.allthatnode.com:26657
            max_connections: 20
        grpc:
            address: cosmoshub.strange.love:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    genesis_file_path: genesis.json
    average_block_time: 5s
database:
    name: bdjuno
    host: localhost
    port: 5432
    user: test
    password: pass
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    port: 3000
```
on running bdjuno parse genesis-file I get the below error
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/51401092/190638712-283c6b1a-7b77-49ed-beae-6994e7c86b52.png">
 
And when I use bdjuno start I get  (I am using public rpc urls for now )
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/51401092/190638767-83eff6ef-0eb9-4dfb-86b6-4c70a94dab99.png">
