### ISSUE TITLE
unexpected inconsistent hasura 

### ISSUE THREAD

**Issue by avenbreaks** [forbole/bdjuno#495]
#476 
hello, i got error, how to fix inconsistent 
 
`unecpected source with name bdjuno inconsistent ` 

root@cosmos-blockchain-client:~/bdjuno/hasura#` hasura metadata apply --endpoint http://51.159.83.41:8080 --admin-secret pass`
FATA[0000] error applying metadata 
{
  "code": "unexpected",
  "error": "source with name \"bdjuno\" is inconsistent",
  "path": "$.args"
} 

![image](https://user-images.githubusercontent.com/93043826/200095458-4768de72-a104-41e5-813e-4f3430622d71.png)

**Comment by avenbreaks** [comment]
and after im trying again 
$ `bdjuno start `
ERROR: failed to start client: websocket: bad handshake

port open : 
```
26657
1317
9090
6060 
```

**Comment by avenbreaks** [comment]
> and after im trying again $ `bdjuno start ` ERROR: failed to start client: websocket: bad handshake
> 
> port open :
> 
> ```
> 26657
> 1317
> 9090
> 6060 
> ```

solved wrong configuration, grpc address in app.toml spn, but i have error again at `bdjuno start` 

`4:51AM ERR error="error while getting comminity pool: rpc error: code = Unknown desc = codespace sdk code 26: invalid height: cannot query with height in the future; please provide a valid height"`

> config.yaml


```
chain:
    bech32_prefix: gitshock
    modules: 
    - modules
    - messages
    - auth
    - actions 
    - bank 
    - consensus 
    - distribution 
    - feegrant 
    - gov 
    - mint
    - pricefeed
    - slashing
node:
    type: remote
    config:
        rpc:
            client_name: gitshock
            address: http://51.159.83.41:26657
            max_connections: 20
        grpc:
            address: http://51.159.83.41:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    genesis_file_path: /root/spn/379/config/genesis.json
    average_block_time: 3s
database:
    name: postgres
    host: localhost
    port: 5432
    user: user
    password: pass
    schema: public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed:
    tokens:
        - name: Atom
          units:
            - denom: uatom
              exponent: 0
            - denom: atom
              exponent: 6
              price_id: cosmos
        - name: Desmos
          units:
            - denom: udsm
              exponent: 0
            - denom: dsm
              exponent: 6
              price_id: desmos
actions:
    port: 3000

```
