### ISSUE TITLE
Cannot query data directly from node

### ISSUE THREAD

**Issue by Im-Kunal-13** [forbole/bdjuno#606]
## Bug description
I'm currently facing some difficulties while trying to query data from the node and test Hasura actions. I've been following the documentation provided at https://docs.bigdipper.live/cosmos-based/parser/hasura. However, I'm encountering a consistent 'connection refused' error when I use the curl command to make the request:
`curl http://localhost:3000/account_balance \ --data '{ "input": { "address": "desmos16fc5kd5d4f5sjq5wz3v8gkyk4xd8f7hrax27xw" } }'`

How can I diagnose and fix the 'connection refused' error that I'm experiencing when I attempt to query data using Hasura actions?

This is my `config.yaml` file 

```
node:
    type: remote
    config:
      rpc:
        client_name: juno
        address: http://localhost:26657
        max_connections: 20
      grpc:
        address: localhost:9090
        insecure: true
parsing:
    workers: 100
    average_block_time: 5s
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    genesis_file_path: ~/.sei/config
    start_height: 1
    fast_sync: true
database:
    url: postgresql://postgres:postgres123@localhost:5432/bdjuno?sslmode=disable&search_path=public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
actions:
    port: 3000
    host: 127.0.0.1
```

## Steps to reproduce
Setting up a postgres database, bdjuno and hasura from here - https://docs.bigdipper.live/cosmos-based/parser/database. Hasura version - v2.27.0
