### ISSUE TITLE
Support for Unicorn Chain

### ISSUE THREAD

**Issue by risasoft** [forbole/bdjuno#751]
Hello - I'm trying to add support for a new chain, Unicorn. I have followed the steps to start syncing but running into an error:

12:54AM ERR re-enqueueing failed block err="failed to get block from node: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). error unmarshalling result: json: cannot unmarshal array into Go value of type map[string]json.RawMessage" height=1296005
12:54AM DBG processing block height=1296005

I think something needs to be customized for this chain. Do you know where to start adding customizations?

Unicorn chain uses 
cosmos_sdk_version | v0.45.10

I have tried different branches with same error:
origin/cosmos/v0.46.x  
chains/comdex/mainnet

Here is my config file:

```
chain:
    bech32_prefix: unicorn
    modules: []
node:
    type: remote
    config:
        rpc:
            client_name: unicornio
            address: https://rpc.unicorn.meme:443
            max_connections: 20
        grpc:
            address: localhost:9090
            insecure: true
parsing:
    workers: 1
    start_height: 1296000
    average_block_time: 5s
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: false

```
